COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    do_checkstyle = False,
)

onos_app (
    app_name = 'org.onosproject.netcfgclientportsprovider',
    title = 'Network Config Client Ports Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'Links provider that uses network config service to predefine links between IP and Optical devices.',
)
