COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//incubator/api:onos-incubator-api',
    '//lib:javax.ws.rs-api',
    '//utils/osgi:onlab-osgi',
    '//cli:onos-cli',
    '//apps/orchestrator/mgr:onos-apps-orchestrator-mgr'
]


osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    do_checkstyle = False,
)
