COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:JACKSON',
  '//drivers/utilities:onos-drivers-utilities',
  '//incubator/api:onos-incubator-api',
  '//protocols/rest/api:onos-protocols-rest-api',
  '//lib:javax.ws.rs-api',
]
osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  resources_root = 'src/main/resources',
  resources = glob(['src/main/resources/**']),
  do_checkstyle = False,
)
onos_app (
  app_name = 'org.onosproject.drivers.cop',
  title = 'Cop Device Drivers',
  category = 'Drivers',
  url = 'http://onosproject.org',
  description = 'ONOS Cop Device Drivers application.',
  required_apps = [ 'org.onosproject.restproxysb'],
)